<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>StoDamageMeter.Launcher</RootNamespace>
    <AssemblyName>Launcher</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    
    <!-- Single-File Publishing -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    
    <!-- Optimization -->
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <!-- Trimming deaktiviert wegen WPF -->
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

</Project>
